# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "fiscal"
main = ".open-next/worker.js"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
binding = "ASSETS"
directory = ".open-next/assets"

[observability]
enabled = true

[placement]
mode = "smart"

[[d1_databases]]
binding = "DATABASE"
database_name = "fiscal-db"
database_id = "491a6d4a-f808-4a3c-bede-ea9da6a3daf8"
migrations_dir = "drizzle"

[[kv_namespaces]]
binding = "KV"
id = "2ace0b2ef65e4da2afebf6511bb3622b"